### ISSUE TITLE
Arabic version of chronology

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/projectjaraid.github.io#3]
@tillgrallert  I created a page "Al-Fihris al-Zamani" in which I intend to display the Arabic file (to which I will turn soon). Do you think this is a good name? 
Also, my goal is to display the Arabic TEI XML file through CETEICean as the English one in this page.

**Comment by tillgrallert** [comment]
I will need some time to address this question as I think it will ultimately require to change the data model even if it only means adding some columns.

**Comment by Mestyan** [comment]
OK - I will do now some visualizations so just take your time

**Comment by tillgrallert** [comment]
Dear @Mestyan, In order to not break your existing code for the website, I propose the following temporal solution:

- we keep the data model as is, i.e. a table with columns of broadly defined content
- I add columns for:
    + title in Arabic
    + names of contributors in Arabic
    + publication places in Arabic

For the necessary correction of the automatic translation of IJMES transcription to Arabic script, I propose to make use of a central authority file. The steps are as follows:

1. I create a new authority file for all
    + persons
    + organizations
    + places
2. I link all references in the master file to the authority file using private IDs
3. I have periodical titles in the master file translated into Arabic script and added as a new column. These can be corrected with search and replace directly in the master file.
4. I have all entries in the authority file translated into Arabic script.
5. Data will be corrected, edited in the authority file
6. At any point, we can pull the corresponding Arabic names of people, organizations, and places from the authority file and add them as new columns to the master file.
     + this step can be repeated ad infinitum whenever corrections have been made to the authority file

**Comment by tillgrallert** [comment]
Dear @Mestyan, I will just create a new issue with the same content on the data repository

**Comment by Mestyan** [comment]
OK, I look forward to this solution. This will be a magnificent work and a great experiment. I am ready to step in with my lame coding and editing skills when the new columns in the master and the authority file is ready. This will be great @tillgrallert

**Comment by Mestyan** [comment]
@tillgrallert please have a look at the display at https://projectjaraid.github.io/pages/chrono.html - I think perhaps it is good to display for human readers the Arabic and the transliterated data together as it is (of course the cleaning should go on). Or, should there be a separate Arabic al-fihris al-zamani? What is your opinion?

**Comment by Mestyan** [comment]
I changed my mind - the separate Arabic display is better - will work on it in the coming days

**Comment by tillgrallert** [comment]
I would suggest to increase the font size for all elements that carry `@xml:lang="ar"`.

**Comment by Mestyan** [comment]
yes thanks I will !

**Comment by Mestyan** [comment]
done thanks to @tillgrallert
